ZAP: sema::Binder Class Reference
sema::Binder Class Reference
#include <binder.hpp>
Public Member Functions
Binder (zap::DiagnosticEngine &diag)
std::unique_ptr< BoundRootNode > bind (RootNode &root)
void visit (RootNode &node) override
void visit (FunDecl &node) override
void visit (ExtDecl &node) override
void visit (BodyNode &node) override
void visit (VarDecl &node) override
void visit (ReturnNode &node) override
void visit (BinExpr &node) override
void visit (ConstInt &node) override
void visit (ConstBool &node) override
void visit (IfNode &node) override
void visit (WhileNode &node) override
void visit (BreakNode &node) override
void visit (ContinueNode &node) override
void visit (AssignNode &node) override
void visit (FunCall &node) override
void visit (ConstId &node) override
void visit (ConstFloat &node) override
void visit (ConstString &node) override
void visit (ConstChar &node) override
void visit (UnaryExpr &node) override
void visit (ArrayLiteralNode &node) override
void visit (EnumDecl &node) override
void visit (RecordDecl &node) override
Public Member Functions inherited from Visitor
virtual ~Visitor () noexcept=default
virtual void visit (Node &)
virtual void visit (TopLevel &)
virtual void visit (StatementNode &)
virtual void visit (ImportNode &)
virtual void visit (ParameterNode &)
virtual void visit (TypeNode &)
virtual void visit (ExpressionNode &)
Private Member Functions
void pushScope ()
void popScope ()
std::shared_ptr< zir::Type > mapType (const TypeNode &typeNode)
void error (SourceSpan span, const std::string &message)
bool isNumeric (std::shared_ptr< zir::Type > type)
bool canConvert (std::shared_ptr< zir::Type > from, std::shared_ptr< zir::Type > to)
std::shared_ptr< zir::Type > getPromotedType (std::shared_ptr< zir::Type > t1, std::shared_ptr< zir::Type > t2)
Private Attributes
zap::DiagnosticEngine & _diag
std::shared_ptr< SymbolTable > currentScope_
std::unique_ptr< BoundRootNode > boundRoot_
std::stack< std::unique_ptr< BoundExpression > > expressionStack_
std::stack< std::unique_ptr< BoundStatement > > statementStack_
std::unique_ptr< BoundBlock > currentBlock_
int loopDepth_ = 0
std::shared_ptr< FunctionSymbol > currentFunction_ = nullptr
bool hadError_ = false
Detailed Description
Definition at line 13 of file binder.hpp.
Constructor & Destructor Documentation
Binder()
sema::Binder::Binder (zap::DiagnosticEngine & diag)
Definition at line 10 of file binder.cpp.
: _diag(diag), hadError_(false) {}
References _diag, and hadError_.
Member Function Documentation
bind()
std::unique_ptr< BoundRootNode > sema::Binder::bind (RootNode & root)
Definition at line 12 of file binder.cpp.
  {
    boundRoot_ = std::make_unique<BoundRootNode>();
    currentScope_ = std::make_shared<SymbolTable>();
    currentScope_->declare("Int", std::make_shared<TypeSymbol>(
                                      "Int", std::make_shared<zir::PrimitiveType>(
                                                 zir::TypeKind::Int)));
    currentScope_->declare(
        "Float",
        std::make_shared<TypeSymbol>(
            "Float", std::make_shared<zir::PrimitiveType>(zir::TypeKind::Float)));
    currentScope_->declare(
        "Bool",
        std::make_shared<TypeSymbol>(
            "Bool", std::make_shared<zir::PrimitiveType>(zir::TypeKind::Bool)));
    currentScope_->declare(
        "Void",
        std::make_shared<TypeSymbol>(
            "Void", std::make_shared<zir::PrimitiveType>(zir::TypeKind::Void)));
    currentScope_->declare(
        "String", std::make_shared<TypeSymbol>(
                      "String", std::make_shared<zir::RecordType>("String")));
    currentScope_->declare(
      "Char",
      std::make_shared<TypeSymbol>(
        "Char", std::make_shared<zir::PrimitiveType>(zir::TypeKind::Char)));
    // Provide `println` as a built-in external function: println(s: String) -> Void
    {
      std::vector<std::shared_ptr<VariableSymbol>> params;
      params.push_back(
        std::make_shared<VariableSymbol>("s",
                         std::make_shared<zir::RecordType>("String")));
      auto retType = std::make_shared<zir::PrimitiveType>(zir::TypeKind::Void);
      auto symbol = std::make_shared<FunctionSymbol>("println", std::move(params), std::move(retType));
      currentScope_->declare("println", symbol);
      boundRoot_->externalFunctions.push_back(
        std::make_unique<BoundExternalFunctionDeclaration>(symbol));
    }
    for (const auto &child : root.children)
    {
      if (auto recordDecl = dynamic_cast<RecordDecl *>(child.get()))
      {
        auto type = std::make_shared<zir::RecordType>(recordDecl->name_);
        if (!currentScope_->declare(recordDecl->name_,
                                    std::make_shared<TypeSymbol>(
                                        recordDecl->name_, std::move(type))))
        {
          error(recordDecl->span,
                "Type '" + recordDecl->name_ + "' already declared.");
        }
      }
      else if (auto enumDecl = dynamic_cast<EnumDecl *>(child.get()))
      {
        auto type =
            std::make_shared<zir::EnumType>(enumDecl->name_, enumDecl->entries_);
        if (!currentScope_->declare(
                enumDecl->name_,
                std::make_shared<TypeSymbol>(enumDecl->name_, std::move(type))))
        {
          error(enumDecl->span,
                "Type '" + enumDecl->name_ + "' already declared.");
        }
      }
    }
    for (const auto &child : root.children)
    {
      if (auto funDecl = dynamic_cast<FunDecl *>(child.get()))
      {
        std::vector<std::shared_ptr<VariableSymbol>> params;
        for (const auto &p : funDecl->params_)
        {
          params.push_back(
              std::make_shared<VariableSymbol>(p->name, mapType(*p->type)));
        }
        std::shared_ptr<zir::Type> retType = nullptr;
        if (funDecl->returnType_)
        {
          retType = mapType(*funDecl->returnType_);
        }
        else if (funDecl->name_ == "main")
        {
          // Default `main` to return Int when no explicit return type given.
          retType = std::make_shared<zir::PrimitiveType>(zir::TypeKind::Int);
        }
        else
        {
          // No explicit return type -> default to Void for other functions.
          retType = std::make_shared<zir::PrimitiveType>(zir::TypeKind::Void);
        }
        auto symbol = std::make_shared<FunctionSymbol>(
            funDecl->name_, std::move(params), std::move(retType));
        if (!currentScope_->declare(funDecl->name_, symbol))
        {
          error(funDecl->span,
                "Function '" + funDecl->name_ + "' already declared.");
        }
      }
      else if (auto extDecl = dynamic_cast<ExtDecl *>(child.get()))
      {
        std::vector<std::shared_ptr<VariableSymbol>> params;
        for (const auto &p : extDecl->params_)
        {
          params.push_back(
              std::make_shared<VariableSymbol>(p->name, mapType(*p->type)));
        }
        auto retType =
          extDecl->returnType_
            ? mapType(*extDecl->returnType_)
            : std::make_shared<zir::PrimitiveType>(zir::TypeKind::Void);
        auto symbol = std::make_shared<FunctionSymbol>(
            extDecl->name_, std::move(params), std::move(retType));
        if (!currentScope_->declare(extDecl->name_, symbol))
        {
          error(extDecl->span,
                "External function '" + extDecl->name_ + "' already declared.");
        }
      }
    }
    root.accept(*this);
    return (hadError_ || _diag.hadErrors()) ? nullptr : std::move(boundRoot_);
  }
References _diag, RootNode::accept(), zir::Bool, boundRoot_, zir::Char, RootNode::children, currentScope_, error(), zir::Float, hadError_, zir::Int, mapType(), and zir::Void.
Referenced by main().
canConvert()
bool sema::Binder::canConvert (std::shared_ptr< zir::Type > from, std::shared_ptr< zir::Type > to) private
Definition at line 838 of file binder.cpp.
  {
    if (from->getKind() == to->getKind())
    {
      if (from->getKind() == zir::TypeKind::Record)
      {
        return from->toString() == to->toString();
      }
      return true;
    }
    if (from->getKind() == zir::TypeKind::Int &&
        to->getKind() == zir::TypeKind::Float)
    {
      return true;
    }
    return false;
  }
References zir::Float, zir::Int, and zir::Record.
Referenced by visit(), visit(), visit(), visit(), visit(), visit(), and visit().
error()
void sema::Binder::error (SourceSpan span, const std::string & message) private
Definition at line 871 of file binder.cpp.
  {
    _diag.report(span, zap::DiagnosticLevel::Error, message);
    hadError_ = true;
  }
References _diag, zap::Error, and hadError_.
Referenced by bind(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), and visit().
getPromotedType()
std::shared_ptr< zir::Type > sema::Binder::getPromotedType (std::shared_ptr< zir::Type > t1, std::shared_ptr< zir::Type > t2) private
Definition at line 860 of file binder.cpp.
  {
    if (t1->getKind() == zir::TypeKind::Float ||
        t2->getKind() == zir::TypeKind::Float)
    {
      return std::make_shared<zir::PrimitiveType>(zir::TypeKind::Float);
    }
    return t1;
  }
References zir::Float.
Referenced by visit(), and visit().
isNumeric()
bool sema::Binder::isNumeric (std::shared_ptr< zir::Type > type) private
Definition at line 832 of file binder.cpp.
  {
    return type->getKind() == zir::TypeKind::Int ||
           type->getKind() == zir::TypeKind::Float;
  }
References zir::Float, and zir::Int.
Referenced by visit(), and visit().
mapType()
std::shared_ptr< zir::Type > sema::Binder::mapType (const TypeNode & typeNode) private
Definition at line 693 of file binder.cpp.
  {
    auto symbol = currentScope_->lookup(typeNode.typeName);
    std::shared_ptr<zir::Type> type = nullptr;
    if (symbol && symbol->getKind() == SymbolKind::Type)
    {
      type = symbol->type;
    }
    else
    {
      if (typeNode.typeName == "Int")
        type = std::make_shared<zir::PrimitiveType>(zir::TypeKind::Int);
      else if (typeNode.typeName == "Float")
        type = std::make_shared<zir::PrimitiveType>(zir::TypeKind::Float);
      else if (typeNode.typeName == "Bool")
        type = std::make_shared<zir::PrimitiveType>(zir::TypeKind::Bool);
      else if (typeNode.typeName == "String")
        type = std::make_shared<zir::RecordType>("String");
      else
        type = std::make_shared<zir::RecordType>(typeNode.typeName);
    }
    if (typeNode.isArray)
    {
      size_t size = 0;
      if (auto constInt = dynamic_cast<ConstInt *>(typeNode.arraySize.get()))
      {
        size = constInt->value_;
      }
      type = std::make_shared<zir::ArrayType>(std::move(type), size);
    }
    if (typeNode.isPointer)
    {
      type = std::make_shared<zir::PointerType>(std::move(type));
    }
    return type;
  }
References TypeNode::arraySize, zir::Bool, currentScope_, zir::Float, zir::Int, TypeNode::isArray, TypeNode::isPointer, sema::Type, and TypeNode::typeName.
Referenced by bind(), visit(), and visit().
popScope()
void sema::Binder::popScope () private
Definition at line 685 of file binder.cpp.
  {
    if (currentScope_)
    {
      currentScope_ = currentScope_->getParent();
    }
  }
References currentScope_.
Referenced by visit(), visit(), and visit().
pushScope()
void sema::Binder::pushScope () private
Definition at line 680 of file binder.cpp.
  {
    currentScope_ = std::make_shared<SymbolTable>(currentScope_);
  }
References currentScope_.
Referenced by visit(), visit(), and visit().
visit() [1/23]
void sema::Binder::visit (ArrayLiteralNode & node) override virtual
Reimplemented from Visitor.
Definition at line 772 of file binder.cpp.
  {
    std::vector<std::unique_ptr<BoundExpression>> elements;
    std::shared_ptr<zir::Type> elementType = nullptr;
    for (const auto &el : node.elements_)
    {
      el->accept(*this);
      if (!expressionStack_.empty())
      {
        auto boundEl = std::move(expressionStack_.top());
        expressionStack_.pop();
        if (!elementType)
        {
          elementType = boundEl->type;
        }
        else if (!canConvert(boundEl->type, elementType))
        {
          error(node.span, "Array elements must have the same type. Expected '" +
                               elementType->toString() + "', but got '" +
                               boundEl->type->toString() + "'");
        }
        elements.push_back(std::move(boundEl));
      }
    }
    auto arrayType = std::make_shared<zir::ArrayType>(
        elementType ? elementType
                    : std::make_shared<zir::PrimitiveType>(zir::TypeKind::Void),
        elements.size());
    expressionStack_.push(
        std::make_unique<BoundArrayLiteral>(std::move(elements), arrayType));
  }
References canConvert(), ArrayLiteralNode::elements_, error(), expressionStack_, Node::span, and zir::Void.
visit() [2/23]
void sema::Binder::visit (AssignNode & node) override virtual
Reimplemented from Visitor.
Definition at line 459 of file binder.cpp.
  {
    auto symbol = currentScope_->lookup(node.target_);
    if (!symbol)
    {
      error(node.span, "Undefined identifier: " + node.target_);
      return;
    }
    auto varSymbol = std::dynamic_pointer_cast<VariableSymbol>(symbol);
    if (!varSymbol)
    {
      error(node.span,
            "Cannot assign to '" + node.target_ + "' (not a variable).");
      return;
    }
    node.expr_->accept(*this);
    if (expressionStack_.empty())
      return;
    auto expr = std::move(expressionStack_.top());
    expressionStack_.pop();
    if (!canConvert(expr->type, varSymbol->type))
    {
      error(node.span, "Cannot assign expression of type '" +
                           expr->type->toString() + "' to variable of type '" +
                           varSymbol->type->toString() + "'");
    }
    statementStack_.push(
        std::make_unique<BoundAssignment>(varSymbol, std::move(expr)));
  }
References canConvert(), currentScope_, error(), AssignNode::expr_, expressionStack_, Node::span, statementStack_, and AssignNode::target_.
visit() [3/23]
void sema::Binder::visit (BinExpr & node) override virtual
Reimplemented from Visitor.
Definition at line 353 of file binder.cpp.
  {
    node.left_->accept(*this);
    if (expressionStack_.empty())
      return;
    auto left = std::move(expressionStack_.top());
    expressionStack_.pop();
    node.right_->accept(*this);
    if (expressionStack_.empty())
      return;
    auto right = std::move(expressionStack_.top());
    expressionStack_.pop();
    auto type = left->type;
    if (node.op_ == "+" || node.op_ == "-" || node.op_ == "*" ||
        node.op_ == "/")
    {
      if (!isNumeric(left->type) || !isNumeric(right->type))
      {
        error(node.span, "Operator '" + node.op_ +
                             "' cannot be applied to types '" +
                             left->type->toString() + "' and '" +
                             right->type->toString() + "'");
      }
      type = getPromotedType(left->type, right->type);
    }
    else if (node.op_ == "~")
    {
      auto isStringOrChar = [](std::shared_ptr<zir::Type> t) {
        if (!t) return false;
        if (t->getKind() == zir::TypeKind::Record)
        {
          return static_cast<zir::RecordType *>(t.get())->getName() == "String";
        }
        return t->getKind() == zir::TypeKind::Char;
      };
      if (!isStringOrChar(left->type) || !isStringOrChar(right->type))
      {
        error(node.span, "Operator '~' can only be applied to 'Char' and 'String' types");
      }
      type = std::make_shared<zir::RecordType>("String");
    }
    else if (node.op_ == "==" || node.op_ == "!=" || node.op_ == "<" ||
             node.op_ == ">" || node.op_ == "<=" || node.op_ == ">=")
    {
      if (!canConvert(left->type, right->type) &&
          !canConvert(right->type, left->type))
      {
        error(node.span, "Incompatible types for comparison: '" +
                             left->type->toString() + "' and '" +
                             right->type->toString() + "'");
      }
      type = std::make_shared<zir::PrimitiveType>(zir::TypeKind::Bool);
    }
    expressionStack_.push(std::make_unique<BoundBinaryExpression>(
        std::move(left), node.op_, std::move(right), type));
  }
References zir::Bool, canConvert(), zir::Char, error(), expressionStack_, zir::RecordType::getName(), getPromotedType(), isNumeric(), BinExpr::left_, BinExpr::op_, zir::Record, BinExpr::right_, and Node::span.
visit() [4/23]
void sema::Binder::visit (BodyNode & node) override virtual
Reimplemented from Visitor.
Definition at line 255 of file binder.cpp.
  {
    auto savedBlock = std::move(currentBlock_);
    currentBlock_ = std::make_unique<BoundBlock>();
    for (const auto &stmt : node.statements)
    {
      stmt->accept(*this);
      if (!statementStack_.empty())
      {
        currentBlock_->statements.push_back(std::move(statementStack_.top()));
        statementStack_.pop();
      }
      else if (!expressionStack_.empty())
      {
        // Expression statement - wrap in BoundExpressionStatement
        auto expr = std::move(expressionStack_.top());
        expressionStack_.pop();
        currentBlock_->statements.push_back(
            std::make_unique<BoundExpressionStatement>(std::move(expr)));
      }
    }
    if (node.result)
    {
      node.result->accept(*this);
      if (!expressionStack_.empty())
      {
        currentBlock_->result = std::move(expressionStack_.top());
        expressionStack_.pop();
      }
    }
  }
References currentBlock_, expressionStack_, BodyNode::result, BodyNode::statements, and statementStack_.
visit() [5/23]
void sema::Binder::visit (BreakNode & node) override virtual
Reimplemented from Visitor.
Definition at line 655 of file binder.cpp.
  {
    if (loopDepth_ <= 0)
    {
      error(node.span, "'break' used outside of loop");
      // push a no-op statement to keep stacks balanced
      statementStack_.push(std::make_unique<BoundExpressionStatement>(nullptr));
      return;
    }
    statementStack_.push(std::make_unique<BoundBreakStatement>());
  }
References error(), loopDepth_, Node::span, and statementStack_.
visit() [6/23]
void sema::Binder::visit (ConstBool & node) override virtual
Reimplemented from Visitor.
Definition at line 734 of file binder.cpp.
  {
    expressionStack_.push(std::make_unique<BoundLiteral>(
        node.value_ ? "true" : "false",
        std::make_shared<zir::PrimitiveType>(zir::TypeKind::Bool)));
  }
References zir::Bool, expressionStack_, and ConstBool::value_.
visit() [7/23]
void sema::Binder::visit (ConstChar & node) override virtual
Reimplemented from Visitor.
Definition at line 434 of file binder.cpp.
  {
    expressionStack_.push(std::make_unique<BoundLiteral>(
        node.value_, std::make_shared<zir::PrimitiveType>(zir::TypeKind::Char)));
  }
References zir::Char, expressionStack_, and ConstChar::value_.
visit() [8/23]
void sema::Binder::visit (ConstFloat & node) override virtual
Reimplemented from Visitor.
Definition at line 421 of file binder.cpp.
  {
    expressionStack_.push(std::make_unique<BoundLiteral>(
        std::to_string(node.value_),
        std::make_shared<zir::PrimitiveType>(zir::TypeKind::Float)));
  }
References expressionStack_, zir::Float, and ConstFloat::value_.
visit() [9/23]
void sema::Binder::visit (ConstId & node) override virtual
Reimplemented from Visitor.
Definition at line 440 of file binder.cpp.
  {
    auto symbol = currentScope_->lookup(node.value_);
    if (!symbol)
    {
      error(node.span, "Undefined identifier: " + node.value_);
      return;
    }
    if (auto varSymbol = std::dynamic_pointer_cast<VariableSymbol>(symbol))
    {
      expressionStack_.push(std::make_unique<BoundVariableExpression>(varSymbol));
    }
    else
    {
      error(node.span, "'" + node.value_ + "' is not a variable.");
    }
  }
References currentScope_, error(), expressionStack_, Node::span, and ConstId::value_.
visit() [10/23]
void sema::Binder::visit (ConstInt & node) override virtual
Reimplemented from Visitor.
Definition at line 414 of file binder.cpp.
  {
    expressionStack_.push(std::make_unique<BoundLiteral>(
        std::to_string(node.value_),
        std::make_shared<zir::PrimitiveType>(zir::TypeKind::Int)));
  }
References expressionStack_, zir::Int, and ConstInt::value_.
visit() [11/23]
void sema::Binder::visit (ConstString & node) override virtual
Reimplemented from Visitor.
Definition at line 428 of file binder.cpp.
  {
    expressionStack_.push(std::make_unique<BoundLiteral>(
        node.value_, std::make_shared<zir::RecordType>("String")));
  }
References expressionStack_, and ConstString::value_.
visit() [12/23]
void sema::Binder::visit (ContinueNode & node) override virtual
Reimplemented from Visitor.
Definition at line 668 of file binder.cpp.
  {
    if (loopDepth_ <= 0)
    {
      error(node.span, "'continue' used outside of loop");
      statementStack_.push(std::make_unique<BoundExpressionStatement>(nullptr));
      return;
    }
    statementStack_.push(std::make_unique<BoundContinueStatement>());
  }
References error(), loopDepth_, Node::span, and statementStack_.
visit() [13/23]
void sema::Binder::visit (EnumDecl & node) override virtual
Reimplemented from Visitor.
Definition at line 822 of file binder.cpp.
  {
    auto symbol = currentScope_->lookup(node.name_);
    auto enumType = std::static_pointer_cast<zir::EnumType>(symbol->type);
    auto boundEnum = std::make_unique<BoundEnumDeclaration>();
    boundEnum->type = enumType;
    boundRoot_->enums.push_back(std::move(boundEnum));
  }
References boundRoot_, currentScope_, and EnumDecl::name_.
visit() [14/23]
void sema::Binder::visit (ExtDecl & node) override virtual
Reimplemented from Visitor.
Definition at line 239 of file binder.cpp.
  {
    auto symbol = std::dynamic_pointer_cast<FunctionSymbol>(
        currentScope_->lookup(node.name_));
    if (!symbol)
    {
      error(node.span,
            "Internal error: External function symbol not found for " +
                node.name_);
      return;
    }
    boundRoot_->externalFunctions.push_back(
        std::make_unique<BoundExternalFunctionDeclaration>(symbol));
  }
References boundRoot_, currentScope_, error(), ExtDecl::name_, and Node::span.
visit() [15/23]
void sema::Binder::visit (FunCall & node) override virtual
Reimplemented from Visitor.
Definition at line 493 of file binder.cpp.
  {
    auto symbol = currentScope_->lookup(node.funcName_);
    if (!symbol)
    {
      error(node.span, "Undefined function: " + node.funcName_);
      return;
    }
    auto funcSymbol = std::dynamic_pointer_cast<FunctionSymbol>(symbol);
    if (!funcSymbol)
    {
      error(node.span, "'" + node.funcName_ + "' is not a function.");
      return;
    }
    if (node.params_.size() != funcSymbol->parameters.size())
    {
      error(node.span, "Function '" + node.funcName_ + "' expects " +
                           std::to_string(funcSymbol->parameters.size()) +
                           " arguments, but received " +
                           std::to_string(node.params_.size()));
    }
    std::vector<std::unique_ptr<BoundExpression>> boundArgs;
    for (size_t i = 0; i < node.params_.size(); ++i)
    {
      node.params_[i]->value->accept(*this);
      if (expressionStack_.empty())
        return;
      auto arg = std::move(expressionStack_.top());
      expressionStack_.pop();
      if (i < funcSymbol->parameters.size())
      {
        auto expectedType = funcSymbol->parameters[i]->type;
        if (!canConvert(arg->type, expectedType))
        {
          error(node.span, "Argument " + std::to_string(i + 1) +
                               " of function '" + node.funcName_ +
                               "' expected type '" + expectedType->toString() +
                               "', but received type '" + arg->type->toString() +
                               "'");
        }
      }
      boundArgs.push_back(std::move(arg));
    }
    expressionStack_.push(
        std::make_unique<BoundFunctionCall>(funcSymbol, std::move(boundArgs)));
  }
References canConvert(), currentScope_, error(), expressionStack_, FunCall::funcName_, FunCall::params_, and Node::span.
visit() [16/23]
void sema::Binder::visit (FunDecl & node) override virtual
Reimplemented from Visitor.
Definition at line 148 of file binder.cpp.
  {
    auto symbol = std::dynamic_pointer_cast<FunctionSymbol>(
        currentScope_->lookup(node.name_));
    if (!symbol)
    {
      error(node.span,
            "Internal error: Function symbol not found for " + node.name_);
      return;
    }
    pushScope();
    auto oldFunction = currentFunction_;
    currentFunction_ = symbol;
    for (const auto &param : symbol->parameters)
    {
      if (!currentScope_->declare(param->name, param))
      {
        error(node.span, "Parameter '" + param->name + "' already declared.");
      }
    }
    if (node.body_)
    {
      node.body_->accept(*this);
    }
    auto boundBody = std::make_unique<BoundBlock>();
    if (currentBlock_)
    {
      boundBody = std::move(currentBlock_);
    }
    popScope();
    currentFunction_ = oldFunction;
    bool hasReturn = false;
    if (boundBody)
    {
      if (boundBody->result)
        hasReturn = true;
      for (const auto &stmt : boundBody->statements)
      {
        if (dynamic_cast<BoundReturnStatement *>(stmt.get()))
        {
          hasReturn = true;
          break;
        }
      }
    }
    if (!hasReturn && symbol->name == "main" &&
        symbol->returnType->getKind() == zir::TypeKind::Int)
    if (!hasReturn && symbol->name == "main" &&
        symbol->returnType->getKind() == zir::TypeKind::Int)
    {
      auto intType = std::make_shared<zir::PrimitiveType>(zir::TypeKind::Int);
      auto lit = std::make_unique<BoundLiteral>("0", intType);
      boundBody->statements.push_back(
          std::make_unique<BoundReturnStatement>(std::move(lit)));
      hasReturn = true;
    }
    if (!hasReturn && symbol->returnType->getKind() != zir::TypeKind::Void)
    {
      // Try to append a default return value for primitive types so code
      // generation succeeds, but still emit a warning.
      auto kind = symbol->returnType->getKind();
      if (kind == zir::TypeKind::Int || kind == zir::TypeKind::Float ||
          kind == zir::TypeKind::Bool)
      {
        std::string litVal = "0";
        if (kind == zir::TypeKind::Float)
          litVal = "0.0";
        else if (kind == zir::TypeKind::Bool)
          litVal = "false";
        auto lit = std::make_unique<BoundLiteral>(litVal, symbol->returnType);
        boundBody->statements.push_back(
            std::make_unique<BoundReturnStatement>(std::move(lit)));
        hasReturn = true;
      }
      _diag.report(node.span, zap::DiagnosticLevel::Warning,
                   "Function '" + node.name_ + "' has non-void return type but no return on some paths.");
    }
    boundRoot_->functions.push_back(
        std::make_unique<BoundFunctionDeclaration>(symbol, std::move(boundBody)));
  }
References _diag, FunDecl::body_, zir::Bool, boundRoot_, currentBlock_, currentFunction_, currentScope_, error(), zir::Float, zir::Int, FunDecl::name_, popScope(), pushScope(), Node::span, zir::Void, and zap::Warning.
visit() [17/23]
void sema::Binder::visit (IfNode & node) override virtual
Reimplemented from Visitor.
Definition at line 545 of file binder.cpp.
  {
    if (!node.condition_)
    {
      error(node.span, "If condition is missing.");
      return;
    }
    node.condition_->accept(*this);
    if (expressionStack_.empty())
      return;
    auto cond = std::move(expressionStack_.top());
    expressionStack_.pop();
    if (cond->type->getKind() != zir::TypeKind::Bool)
    {
      error(node.span, "If condition must be of type 'Bool', but received '" +
                           cond->type->toString() + "'");
    }
    pushScope();
    auto savedMainBlockThen = std::move(currentBlock_);
    node.thenBody_->accept(*this);
    auto thenBound = std::move(currentBlock_);
    currentBlock_ = std::move(savedMainBlockThen);
    popScope();
    std::unique_ptr<BoundBlock> elseBound = nullptr;
    if (node.elseBody_)
    {
      pushScope();
      auto savedMainBlockElse = std::move(currentBlock_);
      node.elseBody_->accept(*this);
      elseBound = std::move(currentBlock_);
      currentBlock_ = std::move(savedMainBlockElse);
      popScope();
    }
    std::shared_ptr<zir::Type> resultType =
        std::make_shared<zir::PrimitiveType>(zir::TypeKind::Void);
    if (thenBound && thenBound->result)
    {
      if (!elseBound || !elseBound->result)
      {
        error(node.span, "If expression with a result must have an 'else' block "
                         "with a result.");
      }
      else
      {
        auto thenType = thenBound->result->type;
        auto elseType = elseBound->result->type;
        if (!canConvert(thenType, elseType) && !canConvert(elseType, thenType))
        {
          error(node.span, "Incompatible types in if branches: '" +
                               thenType->toString() + "' and '" +
                               elseType->toString() + "'");
        }
        resultType = getPromotedType(thenType, elseType);
      }
    }
    auto boundIf = std::make_unique<BoundIfExpression>(
        std::move(cond), std::move(thenBound), std::move(elseBound), resultType);
    if (resultType->getKind() != zir::TypeKind::Void)
    {
      expressionStack_.push(std::move(boundIf));
    }
    else
    {
      statementStack_.push(std::move(boundIf));
    }
  }
References zir::Bool, canConvert(), IfNode::condition_, currentBlock_, IfNode::elseBody_, error(), expressionStack_, getPromotedType(), popScope(), pushScope(), Node::span, statementStack_, IfNode::thenBody_, and zir::Void.
visit() [18/23]
void sema::Binder::visit (RecordDecl & node) override virtual
Reimplemented from Visitor.
Definition at line 807 of file binder.cpp.
  {
    auto symbol = currentScope_->lookup(node.name_);
    auto recordType = std::static_pointer_cast<zir::RecordType>(symbol->type);
    for (const auto &field : node.fields_)
    {
      recordType->addField(field->name, mapType(*field->type));
    }
    auto boundRecord = std::make_unique<BoundRecordDeclaration>();
    boundRecord->type = recordType;
    boundRoot_->records.push_back(std::move(boundRecord));
  }
References boundRoot_, currentScope_, RecordDecl::fields_, mapType(), and RecordDecl::name_.
visit() [19/23]
void sema::Binder::visit (ReturnNode & node) override virtual
Reimplemented from Visitor.
Definition at line 322 of file binder.cpp.
  {
    std::unique_ptr<BoundExpression> expr = nullptr;
    if (node.returnValue)
    {
      node.returnValue->accept(*this);
      if (!expressionStack_.empty())
      {
        expr = std::move(expressionStack_.top());
        expressionStack_.pop();
      }
    }
    if (currentFunction_)
    {
      auto expectedType = currentFunction_->returnType;
      auto actualType =
          expr ? expr->type
               : std::make_shared<zir::PrimitiveType>(zir::TypeKind::Void);
      if (!canConvert(actualType, expectedType))
      {
        error(node.span, "Function '" + currentFunction_->name +
                             "' expects return type '" +
                             expectedType->toString() + "', but received '" +
                             actualType->toString() + "'");
      }
    }
    statementStack_.push(std::make_unique<BoundReturnStatement>(std::move(expr)));
  }
References canConvert(), currentFunction_, error(), expressionStack_, ReturnNode::returnValue, Node::span, statementStack_, and zir::Void.
visit() [20/23]
void sema::Binder::visit (RootNode & node) override virtual
Reimplemented from Visitor.
Definition at line 140 of file binder.cpp.
  {
    for (const auto &child : node.children)
    {
      child->accept(*this);
    }
  }
References RootNode::children.
visit() [21/23]
void sema::Binder::visit (UnaryExpr & node) override virtual
Reimplemented from Visitor.
Definition at line 741 of file binder.cpp.
  {
    node.expr_->accept(*this);
    if (expressionStack_.empty())
      return;
    auto expr = std::move(expressionStack_.top());
    expressionStack_.pop();
    auto type = expr->type;
    if (node.op_ == "-" || node.op_ == "+")
    {
      if (!isNumeric(type))
      {
        error(node.span, "Operator '" + node.op_ +
                             "' cannot be applied to type '" + type->toString() +
                             "'");
      }
    }
    else if (node.op_ == "!")
    {
      if (type->getKind() != zir::TypeKind::Bool)
      {
        error(node.span, "Operator '!' cannot be applied to type '" +
                             type->toString() + "'");
      }
    }
    expressionStack_.push(
        std::make_unique<BoundUnaryExpression>(node.op_, std::move(expr), type));
  }
References zir::Bool, error(), UnaryExpr::expr_, expressionStack_, isNumeric(), UnaryExpr::op_, and Node::span.
visit() [22/23]
void sema::Binder::visit (VarDecl & node) override virtual
Reimplemented from Visitor.
Definition at line 289 of file binder.cpp.
  {
    auto type = mapType(*node.type_);
    std::unique_ptr<BoundExpression> initializer = nullptr;
    if (node.initializer_)
    {
      node.initializer_->accept(*this);
      if (!expressionStack_.empty())
      {
        initializer = std::move(expressionStack_.top());
        expressionStack_.pop();
        if (!canConvert(initializer->type, type))
        {
          error(node.span, "Cannot assign expression of type '" +
                               initializer->type->toString() +
                               "' to variable of type '" + type->toString() +
                               "'");
        }
      }
    }
    auto symbol = std::make_shared<VariableSymbol>(node.name_, type);
    if (!currentScope_->declare(node.name_, symbol))
    {
      error(node.span, "Variable '" + node.name_ + "' already declared.");
    }
    statementStack_.push(std::make_unique<BoundVariableDeclaration>(
        symbol, std::move(initializer)));
  }
References canConvert(), currentScope_, error(), expressionStack_, VarDecl::initializer_, mapType(), VarDecl::name_, Node::span, statementStack_, and VarDecl::type_.
visit() [23/23]
void sema::Binder::visit (WhileNode & node) override virtual
Reimplemented from Visitor.
Definition at line 619 of file binder.cpp.
  {
    if (!node.condition_)
    {
      error(node.span, "While condition is missing.");
      return;
    }
    node.condition_->accept(*this);
    if (expressionStack_.empty())
      return;
    auto cond = std::move(expressionStack_.top());
    expressionStack_.pop();
    if (cond->type->getKind() != zir::TypeKind::Bool)
    {
      error(node.span, "While condition must be of type 'Bool', but received '" +
                           cond->type->toString() + "'");
    }
    pushScope();
    auto savedMainBlockWhile = std::move(currentBlock_);
    loopDepth_++;
    node.body_->accept(*this);
    loopDepth_--;
    auto boundBody = std::move(currentBlock_);
    currentBlock_ = std::move(savedMainBlockWhile);
    popScope();
    std::unique_ptr<BoundWhileStatement> boundWhile =
        std::make_unique<BoundWhileStatement>(std::move(cond),
                                              std::move(boundBody));
    statementStack_.push(std::move(boundWhile));
  }
References WhileNode::body_, zir::Bool, WhileNode::condition_, currentBlock_, error(), expressionStack_, loopDepth_, popScope(), pushScope(), Node::span, and statementStack_.
Member Data Documentation
_diag
zap::DiagnosticEngine& sema::Binder::_diag private
Definition at line 44 of file binder.hpp.
Referenced by bind(), Binder(), error(), and visit().
boundRoot_
std::unique_ptr<BoundRootNode> sema::Binder::boundRoot_ private
Definition at line 46 of file binder.hpp.
Referenced by bind(), visit(), visit(), visit(), and visit().
currentBlock_
std::unique_ptr<BoundBlock> sema::Binder::currentBlock_ private
Definition at line 50 of file binder.hpp.
Referenced by visit(), visit(), visit(), and visit().
currentFunction_
std::shared_ptr<FunctionSymbol> sema::Binder::currentFunction_ = nullptr private
Definition at line 57 of file binder.hpp.
Referenced by visit(), and visit().
currentScope_
std::shared_ptr<SymbolTable> sema::Binder::currentScope_ private
Definition at line 45 of file binder.hpp.
Referenced by bind(), mapType(), popScope(), pushScope(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), and visit().
expressionStack_
std::stack<std::unique_ptr<BoundExpression> > sema::Binder::expressionStack_ private
Definition at line 48 of file binder.hpp.
Referenced by visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), and visit().
hadError_
bool sema::Binder::hadError_ = false private
Definition at line 68 of file binder.hpp.
Referenced by bind(), Binder(), and error().
loopDepth_
int sema::Binder::loopDepth_ = 0 private
Definition at line 52 of file binder.hpp.
Referenced by visit(), visit(), and visit().
statementStack_
std::stack<std::unique_ptr<BoundStatement> > sema::Binder::statementStack_ private
Definition at line 49 of file binder.hpp.
Referenced by visit(), visit(), visit(), visit(), visit(), visit(), visit(), and visit().
The documentation for this class was generated from the following files:
src/sema/binder.hpp
src/sema/binder.cpp